name: "✨ New Shimeji Submission"
description: Submit your own shimeji to Shijima's Featured tab
title: "[New Shimeji]: (Write your shimeji's name here...)"
labels: ["New Shimeji"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting your shimeji to Shijima's featured page!
        Your contributions will make shimeji more accessible to everyone.
        
        > [!TIP]
        > Make sure to take a look at some of the existing shimeji before submitting your own shimeji. This may help you understand the questions better.

  - type: input
    id: shimeji-name
    attributes:
      label: >-
        What is your shimeji called? Most of the time, this is the depicted
        character's name.
    validations:
      required: true

  - type: input
    id: shimeji-source
    attributes:
      label: >-
        What is the source material for this shimeji? Is it from a TV show,
        anime, video game or something else? Is it your original character?
    validations:
      required: true

  - type: textarea
    id: shimeji-actions
    attributes:
      label: >-
        How complex or simple is your shimeji? Does it have any unique
        actions, hotspots or affordances? (Your shimeji does not have to
        be complicated or special. However, if your shimeji has some unique
        traits, you can describe them here.)
    validations:
      required: false

  - type: textarea
    id: shimeji-description
    attributes:
      label: >-
        What should be shown in the "Description" field for the shimeji? This
        can be a funny quote from the character, an inside joke for those
        familiar with the character's lore, or a generic description of the
        character.
    validations:
      required: true

  - type: input
    id: shimeji-url
    attributes:
      label: >-
        Where can users download your shimeji? Preferably, this will be a link to
        a social media post or your own website with a shimeji download link
        somewhere on the page.
    validations:
      required: true

  - type: input
    id: artist-name
    attributes:
      label: >-
        What is your name? What should be displayed next to the "Artist" or "Creator"
        labels within Shijima?
    validations:
      required: true

  - type: input
    id: artist-url
    attributes:
      label: >-
        Where can users find you? This could be your DeviantArt, Tumblr or Twitter page,
        your website or something else.
    validations:
      required: true

  - type: input
    id: preview-filename
    attributes:
      label: >-
        Which image within the shimeji should be used as the preview image in Shijima?
        (e.g. shime1.png)
    validations:
      required: true
  
  - type: checkboxes
    id: test-confirmation
    attributes:
        label: You must test the shimeji with Shijima before submitting it here.
        description: >-
          You can test your shimeji with [Shijima-Qt](https://github.com/pixelomer/Shijima-Qt) on
          your PC. Alternatively, as a shimeji creator, you may be eligible to receive a free copy
          of [Shijima-iOS](https://havoc.app/package/shijima). Please note that a jailbroken
          iPhone or iPad is required if you want to use Shijima-iOS.
        options:
          - label: 'I have tested the shimeji with Shijima and confirmed that it works as expected'
            required: true
  
  - type: checkboxes
    id: content-confirmation
    attributes:
        label: Your submission must comply with the submission guidelines to be accepted.
        description: |
          - Submission guidelines: https://github.com/pixelomer/Shijima-Featured/blob/main/submission_guidelines.md
          - GitHub's site policy: https://docs.github.com/en/site-policy
        options:
          - label: 'My submission is compliant with the submission guidelines'
            required: true
    
  - type: checkboxes
    id: rights-confirmation
    attributes:
        label: "Grant of rights: You must read grant_of_rights.md and agree to it to submit your shimeji."
        description: |
          (This document only applies to shimeji submitted to https://github.com/pixelomer/Shijima-Featured through GitHub issues after July 13, 2025.)

          In this text,

          - Shijima refers to any past, current and future versions of Shijima developed
          by pixelomer including Shijima-Qt, Shijima-iOS, Shijima-Wii, Shijima-NX
          and Shijima-Android.
          - Content refers to the shimeji identified by your submission, and the
          other information your provided as a part of your submission.

          You retain all of your ownership rights to your Content. What belongs to
          you stays yours. However, to submit your Content to Shijima, you are
          required to grant some rights to pixelomer, the developer of Shijima.

          By submitting your Content to this repository, you grant to pixelomer
          a worldwide, non-exclusive, royalty-free, transferable, sublicensable
          license to use your Content (including to reproduce, distribute, modify,
          display and perform it) for the purpose of operating, promoting, and
          improving Shijima.

          You also grant each other user of Shijima a worldwide, non-exclusive,
          royalty-free license to access your Content through Shijima, and to use
          that Content (including to reproduce, distribute, modify, display, and
          perform it) only as enabled by a feature of Shijima.
        options:
          - label: 'I have read [grant_of_rights.md](https://github.com/pixelomer/Shijima-Featured/blob/8f654abd2e2de6ec8ce9c486e04f527a0dd4ea5b/grant_of_rights.md) and I agree to it.'
            required: true
